### ISSUE TITLE
Hashes of ROMs

### ISSUE THREAD

**Issue by zensurette** [Gekkio/gb-hardware-db#3]
Please add the hashes of the ROMs to the metadata.

Without the SHA1 of the ROMs it is not possible to associate your scans with related entries in other databases.

**Comment by Gekkio** [comment]
It's not possible in general, because submissions don't involve ROM dumping. The identity of each ROM comes from the ROM chip code (e.g. "DMG-A6SP-0" or "DMG-L6J-2"), which can be seen visually. However, I try to use No-Intro naming for games so there's a more user-friendly link between the two databases.

**Comment by Gekkio** [comment]
I've decided to add ROM SHA256 as an **optional** field to submissions. But my original point still stands: No-Intro naming and/or the mask ROM code should be the main ways of associating submissions with other databases.
